name: Backend CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v2

      - name: Installing dependencies
        run: npm ci

      - name: Building
        run: npm run build

      - name: Linting
        run: npm run lint -- --max-warnings=0
